FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y \
      systemd \
      sudo \
      lsb-release \
      snapd \
      curl \
      wget \
      netcat-openbsd

ENTRYPOINT ["/lib/systemd/systemd"]
